language: node_js
node_js:
  - 12.14.0
cache:
  directories:
    - node_modules
before_install:
  - sudo apt-get update
  - sudo apt-get -y install ruby openjdk-8-jre
before_script:
  - export NODE_OPTIONS=–max_old_space_size=4096
script:
  - npm install -g codecov
  - npm test && codecov
  - CI=false npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master